### ISSUE TITLE
Unable to create an account or to to continue without an account on the sofa app

### ISSUE THREAD

**Issue by nicolas-heigvd** [MediaComem/modos#104]
When clicking on "Créer le compte" on https://modos.isc.heia-fr.ch/ after having filled the fields, the route https://modos.isc.heia-fr.ch/api/v1/users returns a 502 error "Bad Gateway" (nginx).

And trying to continue without an account loops back on the account creation page after having clicked on "Terminer" when selected the age category.

**Comment by damieng002** [comment]
There was a change from the HEIA-FR servers that prevented the service from running.
Everything works again.

**Comment by nicolas-heigvd** [comment]
Indeed, the site seems fully functional now. Thanks @damieng002 !
