### ISSUE TITLE
App name, logo & meta

### ISSUE THREAD

**Issue by randsom** [MediaComem/modos#19]
- [x]  **App name**

Please change the actual name ("MoDoS Contributor") to : 

_modos Explorer_

- [x]  **Logo**

The current logo is the Ionic default app logo. It should be set to the actual modos logo ([modos-Logo.zip](https://github.com/MediaComem/modos/files/5050682/modos-Logo.zip)), so it appears : 

- As the app icon 

- In the splash screen (when launching)

- [x]  **Meta**

Please proceed to a check of the meta-informations and manifest of the app, so the basic informations are not left by default (name, author(s), etc.)

**Comment by verdonarthur** [comment]
For the metadata, there is basicaly nothing in the app now. Most of them are set when the app is publish on the store.
