### ISSUE TITLE
HomeScreen - Review content & Slight changes to the layout

### ISSUE THREAD

**Issue by randsom** [MediaComem/modos#20]
- [x] **Catch phrase**

Change: 

_Signalez les obstacles à la mobilité piétonne en un clin d'oeil.
Vos observations aident à rendre les villes plus accessibles !_

- [x] **Contribution button**

Set to : 

_Signaler un obstacle_

- [x] **Layout rework**

See : 
![image](https://user-images.githubusercontent.com/16078442/89791842-1a040c80-db24-11ea-8449-4b4193fceacb.png)

**Comment by verdonarthur** [comment]
Do I also change the color of the button to be the same as the header ? Because It's seems better to me that we too much different color on the same page
