### ISSUE TITLE
Obstacle selection - Contents & layout rework

### ISSUE THREAD

**Issue by randsom** [MediaComem/modos#22]
- [x] **Change categories names using `title_fr` reference below**

api name | picto file | title_fr
-- | -- | --
coating | coating | Problème de revêtement
obstacle | obstacle_in_path | Obstacle sur le passage
security | security_traffic | Sécurité, danger
passability | passability | Franchissabilité
slope | slope | Forte pente
width | sidewalk_width | Largeur de trottoir
other | other | Autre observation

- [x] **Change Title**

> TYPE D'OBSTACLE
> _Choisissez le type d'obstacle que vous allez photographier_

- [x] **Change cards background color**
Use : #E5E5E5

![image](https://user-images.githubusercontent.com/16078442/89903986-a841c680-dbe8-11ea-8f59-a47802d26e3d.png)

- [x]  Note the color change on the pages header. Actually, it is light purple (#826DAE) -> Please change to navy blue #192145 **for all pages header**. _This color should already be set in the CSS variables_

**Comment by verdonarthur** [comment]
Color #192145  is not referenced in the css vars but I will add it.
