### ISSUE TITLE
GPS access rules & Manual geolocation

### ISSUE THREAD

**Issue by randsom** [MediaComem/modos#30]
The following use case has been decided for the GPS access

- The user is asked to give access to the phone's GPS **directly after the first login**
  - If the user allows it ; it is **saved** and never asked again. He can do contribution as he pleases. 
  - If the user refuses it ; he is reminded he has to give access to the GPS as soon as he tries to make a contribution
  - If the user still refuses ; the above goes on
- **No contribution is allowed without the GPS access**

**Comment by verdonarthur** [comment]
For "how android and Ionic manage permission" reasons: the mentionned use case has been adapted. Here's how:


- The user is asked to give access to the phone's GPS directly after the first login
  - If the user allows it ; it is saved and never asked again (but he can change it into the app permission settings of android). He can do contribution as he pleases.
  - If the user refuses it ; User get a message that without localisation, the app can't work and the App exit. The app will exit after login as long as the user do not allow it in the android permission.
- No contribution is allowed without the GPS access (App exit)
