### ISSUE TITLE
Unable to connect with username and password from v.0

### ISSUE THREAD

**Issue by nicolas-heigvd** [MediaComem/modos#38]
I'm no more able to connect to the Early App for field data collection using my previous username and password and there is no way to create a new one from the home page of the App.

I'm using the latest release (modos Explorer v0.1.1).

**Comment by verdonarthur** [comment]
All test data have been wiped since last migration to postgres. There is no way to create an account because it is wanted. To create a new account you must use the api: https://modos.heig-vd.ch/api/v1/doc/#/users/createUser
