### ISSUE TITLE
Why not using environment variable defined in dotenv here?

### ISSUE THREAD

**Issue by nicolas-heigvd** [MediaComem/modos#44]
https://github.com/MediaComem/modos/blob/9fe0a7d2538b745d402bcd6bb3612ad4cae7f6c0/packages/backend/docker-compose.yml#L13

db name seems outdated ?

**Comment by verdonarthur** [comment]
it's a docker-compose file so you can not use dot env variables here...
And if you look at the rest of this docker-compose file you'll see that there is another instanciated container that create a db with that name.
Also this docker-compose is only for testing and will not be used in production.
