### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by nicolas-heigvd** [MediaComem/modos#45]
I have this issue after starting the project locally:

![image](https://user-images.githubusercontent.com/35065252/97666418-f050e680-1a7d-11eb-868c-7b35218cd037.png)

The server doesn't throw any error.

It happens both if the project is started natively or with it's docker counterpart.

Did I miss something, such as an environment variable or something else?

**Comment by verdonarthur** [comment]
It's perfectly normal as there is no route on /
