### ISSUE TITLE
Set more decimals on GPS values collected by the mobile application

### ISSUE THREAD

**Issue by nicolas-heigvd** [MediaComem/modos#58]
Current positions are not enough accurate; their precision is higher than 11m in some cases.

![image](https://user-images.githubusercontent.com/35065252/99532692-fa8f4200-29a4-11eb-81db-5f843d46aed4.png)

I would recommend to store GPS values up to the 5 or 6th decimal, if available. 

Maybe the 3 or 4-digits values were the one collected when `enableHighAccuracy` was not set to `true`?

**Comment by oertz** [comment]
Well in your screenshot there are already real numbers with 5 digits. Also if I'm correct :

1° 			= 111000m
0.1° 		= 11100m
0.01° 		= 1110m 
0.001°		= 111m
0.0001° 		= 11.1m
0.00001°		= 1.11m (5 digits)

I've in mind that 6 digits is almost the ultimate limit for commercial GPS devices.

But before that the questions could be :
- what is the storage type configured in DB physical model?
- is there a memory vehicle and/or an rounding operation in the middle that is smaller from GPS device to DB storage?
- is there a parameter with device API to set something about that (I doubt, generally it provides even too much digits) ?

Finally, on the map, it looks like it is of a good result ... but may be we should check it is not just by chance.

My 2cts.

**Comment by nicolas-heigvd** [comment]
You are absolutely right, but it's curious that we have latitude values with only 3 or 4 digits, even if it's physically possible to be at 37.42200, it sounded strange to me, I just wanted to make sure everything was done correctly.

**Comment by oertz** [comment]
Yes, let's check if we are not loosing information at the beginning, in the middle or in the storage. It's worth to be done even if we know that a geolocation is never stable (https://blog.oplopanax.ca/wp-content/uploads/2012/11/GPS-Accuracy.png).

**Comment by verdonarthur** [comment]
I've checked that and the precision is not up to me: https://github.com/apache/cordova-plugin-geolocation/issues/174
